### ISSUE TITLE
Prepare the Tempo Operator to be released

### ISSUE THREAD

**Issue by iblancasa** [grafana/tempo-operator#183]
This task is to track the different changes needed to create a release of the Tempo Operator.
* [x] Add versioning to the code: add a `version` subcommand listing the versions of the different components. Also, provide a data structure to use the version in different parts of the code
* [*] ~Adapt the Dockerfile and Makefile to read the desired version to use for Tempo and Tempo Operator and build the source code correctly~
* [ ] ~Add automation to make easy the modification of the Tempo images and the generation of the bundle with the correct version~
* [ ] ~ocument all the manual steps that need to be performed~

**Comment by pavolloffay** [comment]
This is dup/related to #3

**Comment by pavolloffay** [comment]
@rubenvp8510 I am assiging it to you since you have already started. 

Based on #344 there are some missing pieces

- [ ] introduce GHA for changelog check and label for skipping the changelog
- [ ] Document how to find new versions of component images - maybe directly in `config/manager/controller_manager_config.yaml`
