### ISSUE TITLE
Local Backend type

### ISSUE THREAD

**Issue by gunpuz** [grafana/tempo-operator#709]
How to deploy tempo without `s3`, `gcs`, `azure` using only "plain" kubernetes?

Tempo docs says there is fourth option - `local`
https://github.com/grafana/tempo/blob/56fbbcd107f7853e3e8f64df1e22f37a24cd367f/docs/sources/tempo/operations/tempo_cli.md?plain=1#L43

```md
`--backend <value>` The storage backend type, one of `s3`, `gcs`, `azure`, and `local`.
```

Here seems to be only 3 options:
https://github.com/grafana/tempo-operator/blob/5a79e619f268dac0fefd6cc394555582b17de520/apis/tempo/v1alpha1/storage.go#L21

**Comment by andreasgerstmayr** [comment]
hi @gunpuz!

Tempo supports local filesystem mode only in the [monolithic deployment mode](https://grafana.com/docs/tempo/latest/setup/deployment/#monolithic-mode), because all components need to access the same disk: https://grafana.com/docs/tempo/latest/configuration/#storage

At the moment the Tempo operator only supports the [microservices deployment mode](https://grafana.com/docs/tempo/latest/setup/deployment/#microservices-mode). However, I'm currently working on supporting the monolithic mode, which will support local filesystem storage (in a PersistentVolume) and also in-memory storage: #710.

**Comment by andreasgerstmayr** [comment]
I'm closing this in favor of #710, which is already worked on here: #722.
